# Generated by Django 4.2.9 on 2024-02-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='suggested_calories',
            field=models.FloatField(default=0),
        ),
    ]
