# Generated by Django 4.2.9 on 2024-02-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_weightentry_bmi_weightentry_suggested_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='bmi',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
