# Generated by Django 4.2.9 on 2024-02-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_weight',
        ),
    ]
